spring.application.name=cookigram3
# MongoDB
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/cookigramdb}

# Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# Server
server.port=8080

# Logging
logging.level.org.springframework.security=INFO
logging.level.com.cookigram=DEBUG